version: '3'

services:
  web:
    hostname: magento2.test
    container_name: magento2web
    restart: always
    build: .
    environment:
      - PHP_IDE_CONFIG=serverName=PHPSTORM
      - MAGENTO_CLOUD_CLI_TOKEN
      - COMPOSER_AUTH
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - src-volume:/var/www/html
      - src-composer-cache-volume:/root/.composer/cache
    cap_add:
      - "SYS_PTRACE"
  db:
    container_name: magento2db
    image: mariadb:10.7.1
    restart: always
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    ports:
      - "3306:3306"
    volumes:
      - "./etc/mysql:/etc/mysql/conf.d"
      - db-volume:/var/lib/mysql
volumes:
  src-volume:
  db-volume:
  src-composer-cache-volume:
